# -*- coding: utf-8 -*-
"""N/Y_adult.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1urTMh2GdTYwHp2OQvh5cHnsM4z0_zWZ4

## Датасеты

В результате работы получатся следующие датасеты
"""

import pandas as pd

start_path = '/content/drive/MyDrive/University/4 course/АОЕЯ/лаба'

book_df = pd.read_csv(start_path + '/books_csv.csv')

words_stats_df = pd.read_csv(start_path + '/b_word_stats.csv')

en_analyze_df = pd.read_csv(start_path + '/en_analyze_csv.csv')

ru_analyze_df = pd.read_csv(start_path + '/ru_analyze_csv.csv')

readability_en_df = pd.read_csv(start_path + '/readability_en_df.csv')

readability_ru_df = pd.read_csv(start_path + '/readability_ru_df.csv')

"""#### Данные в датасетах"""

book_df.columns

"""Столбцы с аннотацией, текстом и обработанными вариантами убраны в соответствии с авторским правом."""

book_df[['id', 'title', 'author', 'language', 'country', 'year', 'pages', 'word_count',
       'sent_count', 'char_count']].head()

words_stats_df

en_analyze_df.columns

en_analyze_df[['id', 'title', 'author', 'year', 'pages', 'word_count', 'ttr', 'mattr',
       'pos_dist_50k', 'pos_dist_100k', 'pos_dist']]

en_analyze_df[['id', 'title', 'ttr','mattr']]

ru_analyze_df[['id', 'title', 'author', 'year', 'pages', 'word_count', 'ttr', 'mattr',
       'pos_dist_50k', 'pos_dist_100k', 'pos_dist']]

ru_analyze_df[['id', 'title', 'ttr','mattr']]

readability_en_df.columns

readability_en_df[['id', 'title', 'flesch_reading_ease', 'flesch_kincaid_grade', 'gunning_fog', 'smog_index', 'automated_readability','dale_chall']]

readability_ru_df[['id', 'title', 'flesch_ru', 'smog_ru', 'avg_syl_per_word','avg_sent_len']]

"""## Перевод из epub в txt"""

!pip install ebooklib beautifulsoup4 -q

output_dir = '/books'  # папка для сохранения

# список файлов
epub_files = ['']

import os
import ebooklib
from ebooklib import epub
from bs4 import BeautifulSoup
from pathlib import Path

BLOCKLIST = ['[document]', 'noscript', 'header', 'html', 'meta', 'head', 'input', 'script']

def chapter_to_text(chapter_content: bytes) -> str:
    soup = BeautifulSoup(chapter_content, 'html.parser')
    output, prev = [], ''
    for tag in soup.find_all(string=True):
        if tag.parent.name not in BLOCKLIST and not tag.isspace():
            if not (str(prev).endswith(' ') or str(tag).startswith(' ')):
                output.append('\n\n')
            output.append(str(tag))
            prev = tag
    return ''.join(output)

def convert(epub_path: str, output_dir: str) -> str:
    os.makedirs(output_dir, exist_ok=True)
    book = epub.read_epub(epub_path)
    txt_path = os.path.join(output_dir, Path(epub_path).stem + '.txt')

    with open(txt_path, 'w', encoding='utf-8') as f:
        for item in book.get_items():
            if item.get_type() == ebooklib.ITEM_DOCUMENT:
                f.write(chapter_to_text(item.get_content()) + '\n')

    print(f"✅ Готово: {txt_path}")
    return txt_path

for f in epub_files:
    convert(f, output_dir)

"""## Перевод из m4a в txt"""

!pip install openai-whisper -q
!apt-get install -y ffmpeg -q  # нужен для обработки аудио

import whisper
import os
import glob
from pathlib import Path
from natsort import natsorted  # правильная сортировка: глава2 < глава10

# natsort нет в Colab по умолчанию
os.system('pip install natsort -q')
from natsort import natsorted

# Поддерживаемые форматы: mp3, mp4, m4a, wav, ogg, flac, wma
audio_folder = ''
output_txt  = ''
model_size = 'medium'

extensions = ('*.mp3', '*.m4a', '*.wav', '*.ogg', '*.flac', '*.wma')
audio_files = []
for ext in extensions:
    audio_files.extend(glob.glob(os.path.join(audio_folder, ext)))

# Сортировка по естественному числовому порядку (глава1, глава2, ..., глава10)
audio_files = natsorted(audio_files)

####### все файлы
if not audio_files:
    print("❌ Файлы не найдены. Проверь путь к папке.")
else:
    print(f"📚 Найдено файлов: {len(audio_files)}")
    for f in audio_files:
        print(f"  • {Path(f).name}")

####### выбрать файлы
# главы с 2-й по 20-ю включительно
selected_files = audio_files[0:19]  # Python: индекс 1 = 2‑я глава, 19 = 20‑я

print(f'Всего файлов: {len(audio_files)}')
print(f'Будем обрабатывать: {len(selected_files)}')
for f in selected_files:
    print(f)

model = whisper.load_model(model_size)

# Папка для промежуточных txt по каждой главе (на случай обрыва)
chapters_dir = str(Path(output_txt).parent / 'chapters_temp')
os.makedirs(chapters_dir, exist_ok=True)

for i, audio_file in enumerate(audio_files, start=1):
    chapter_name = Path(audio_file).stem
    chapter_txt  = os.path.join(chapters_dir, f'{i:03d}_{chapter_name}.txt')

    # Пропускаем уже обработанные главы (возобновление после обрыва)
    if os.path.exists(chapter_txt):
        print(f"⏭️  Глава {i}/{len(audio_files)} уже готова, пропускаем: {chapter_name}")
        continue

    print(f"\n🎧 Глава {i}/{len(audio_files)}: {chapter_name}")
    result = model.transcribe(audio_file, language='ru', verbose=False)

    with open(chapter_txt, 'w', encoding='utf-8') as f:
        f.write(result['text'].strip())

    print(f"✅ Сохранена: {chapter_txt}")

print("\n🔗 Объединяем главы в один файл...")

# Сборка всех глав в правильном порядке
chapter_files = natsorted(glob.glob(os.path.join(chapters_dir, '*.txt')))
with open(output_txt, 'w', encoding='utf-8') as out:
    for chapter_file in chapter_files:
        chapter_name = Path(chapter_file).stem
        with open(chapter_file, 'r', encoding='utf-8') as f:
            out.write(f.read())

print(f"\n📖 Итоговый файл сохранён: {output_txt}")

# Папка с исходными txt
chapters_dir = '/chapters_temp'
# Путь к итоговому файлу
output_txt  = ''

# Собираем все txt-файлы и сортируем "по‑человечески" (001, 002, 010 и т.п.)
chapter_files = natsorted(glob.glob(os.path.join(chapters_dir, '*.txt')))

with open(output_txt, 'w', encoding='utf-8') as out:
    for chapter_file in chapter_files:


        with open(chapter_file, 'r', encoding='utf-8') as f:
            out.write(f.read())
            out.write('\n')  # чтобы между файлами была пустая строка

print(f"\n📖 Итоговый файл сохранён: {output_txt}")

"""## Обработка датасета

Далее проводилось добавление текстов в csv таблицу, предобработка столбцов.
"""

import pandas as pd

# путь к csv
csv_path = '/books_csv.csv'
# папка с txt-файлами: 1.txt, 2.txt, 3.txt, ...
txt_dir = ''

## добавление текстов
df = pd.read_csv(csv_path)

def load_text(book_id):
    txt_path = Path(txt_dir) / f'{book_id}.txt'
    if not txt_path.exists():
        print(f'⚠️ Нет файла для id={book_id}: {txt_path}')
        return None    # или '' если не хочешь пропусков
    with open(txt_path, 'r', encoding='utf-8') as f:
        return f.read()

df['text'] = df['id'].apply(load_text)

# важное место: сохраняем в ТОТ ЖЕ файл
df.to_csv(csv_path, index=False, encoding='utf-8')
print('✅ Готово, файл обновлён по тому же пути:', csv_path)

'''------------ЗАГРУЗКА book_df------------'''
book_df = pd.read_csv('/books_csv.csv')

# заменить данные в 6 строке
book_df.loc[book_df['id'] == 7, ['title', 'author', 'year', 'pages']] = ['Подари мне небо', 'Айлин Грин', '2024', '310']
book_df

'''------------ОБНОВЛЕНИЕ book_df------------'''

csv_path = '/books_csv.csv'

book_df.to_csv(csv_path, index=False, encoding='utf-8')
print('✅ CSV обновлён по пути:', csv_path)

string = book_df[book_df['id'] == 6]['text'].astype(str).iloc[0]
string

## удаление части строки (структурная разметка / )
row_mask = book_df['id'] == 6          # строка с нужным id
col = 'text'                      # нужный столбец
old = 'Издательство «Эксмо». Селина Алин. Игрок. Читают Светлана Маврина и Егор Сазыкин.'            # что удалить

book_df.loc[row_mask, col] = book_df.loc[row_mask, col].str.replace(old, '', regex=False)

book_df.to_csv(csv_path, index=False, encoding='utf-8')

## замена данных в pages
row_mask = book_df['id'] == 8
col = 'pages'

book_df.loc[row_mask, col] = 448

"""### Предобработка annotation and text"""

!pip install pymorphy3 regex -q

import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('omw-1.4')

import numpy as np

import string
import regex as re
import pandas as pd

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk import pos_tag

import pymorphy3 as pm3

# стоп-слова
eng_stopwords = set(stopwords.words('english'))
ru_stopwords  = set(stopwords.words('russian'))

# лемматизаторы
morph = pm3.MorphAnalyzer()       # русский
lemmatizer = WordNetLemmatizer()  # английский


def nltk_pos_tag(word):
    """Простейшее преобразование POS из NLTK в WordNet."""
    tag = pos_tag([word])[0][1][0].upper()
    tag_dict = {'J': 'a', 'N': 'n', 'V': 'v', 'R': 'r'}
    return tag_dict.get(tag, 'n')

csv_path = '/books_csv.csv'

book_df.to_csv(csv_path, index=False, encoding='utf-8')
print('✅ CSV обновлён по пути:', csv_path)

"""#### Преобработка текста"""

def preprocessing(line,
                  lang='en',
                  remove_punctuation=True,
                  remove_stopwords=True,
                  normalisation=True):
    # нижний регистр
    line = line.lower()

    # удаляем разметку глав
    patterns = [
        r'(^|\n)\s*part\s+[a-z0-9ivx]+',
        r'(^|\n)\s*chapter\s+[a-z0-9ivx]+',
        r'(^|\n)\s*глава\s+[а-яё0-9ivx]+',
        r'(^|\n)\s*часть\s+[а-яё0-9ivx]+',
    ]
    for pat in patterns:
        line = re.sub(pat, r'\1 ', line)

    # переносы → пробелы
    line = re.sub('\n\t', ' ', line)

    # оставляем только рус/англ буквы, цифры и пунктуацию
    line = re.sub(r'[^а-яёa-z0-9\s{}]'.format(string.punctuation), '', line)

    # убрать пунктуацию
    if remove_punctuation:
        line = re.sub(r"[{}]".format(string.punctuation), " ", line)

    # токенизация по пробелам
    words = [x for x in re.split(r'\s+', line) if x]

    # удаление стоп-слов
    if remove_stopwords:
        stop_words = eng_stopwords if lang == 'en' else ru_stopwords
        words = [x for x in words if x not in stop_words]

    # лемматизация
    if normalisation:
        lemmas = []
        if lang == 'ru':
            for x in words:
                p = morph.parse(x)[0]
                lemmas.append(p.normal_form)
        elif lang == 'en':
            for x in words:
                pos = nltk_pos_tag(x)
                lemmas.append(lemmatizer.lemmatize(x, pos))
        else:
            lemmas = words
    else:
        lemmas = words

    return ' '.join(lemmas)

line = book_df[book_df['id'] == 1]['annotation'].astype(str).iloc[0]
line

string_ann = book_df.loc[book_df['id'] == 1, 'annotation'].astype(str).iloc[0]
print(preprocessing(string_ann, lang='en'))

def preprocess_row(row):
    text = row['text']
    if pd.isna(text):
        return ''

    lang_col = str(row['language']).lower()

    if 'en' in lang_col:
        lang = 'en'
    else:
        lang = 'ru'

    return preprocessing(str(text), lang=lang)

book_df['text_clean'] = book_df.apply(preprocess_row, axis=1)

book_df.to_csv(csv_path, index=False, encoding='utf-8')
print('✅ Готово, колонка добавлена и csv обновлён')

mask = book_df['id'] == 4
book_df.loc[mask, 'author'] = 'Christina Lauren'

"""## EDA (Разведочный анализ данных)

* Базовая статистика – N слов, символов, слогов, предложений, длина слова (ср, мин, макс, медиана, ст. отклонение), индексы читаемости, частеречный состав, лексическое разнообразие (TTR, Type Token Ratio)

* Частотный анализ – топ N слов в русских и переводных книгах и др.
* Распределение по метаинформации (по издательству, полу автора, оригинальному языку, году издания, возрастному маркеру и т.п.).
* Распределение базовой статистики по метаинформации (объем книг по авторам, году издания и др.)
* Построение графиков и визуализация
"""

'''------------ЗАГРУЗКА book_df------------'''
book_df = pd.read_csv('/books_csv.csv')

'''------------ОБНОВЛЕНИЕ book_df------------'''
csv_path = '/books_csv.csv'

book_df.to_csv(csv_path, index=False, encoding='utf-8')

"""#### Добавление новых столбцов

Одна книга для примера
"""

one_book = book_df[book_df['id'] == 1]['text'].astype(str).iloc[0]

"""### Статистика по словам

Подсчет количества символов (без перевода строк, без пробелов)
"""

s = list(str(one_book).replace('\n', '').replace('\r', '').replace(' ', ''))
len(s)

print(s)

def count_chars_in_book(row) -> int:
    text = str(row['text'])
    s = text.replace('\n', '').replace('\r', '').replace(' ', '')
    return len(s)

book_df['char_count'] = book_df.apply(count_chars_in_book, axis=1)

book_df[['id', 'title', 'author', 'char_count']]

book_df[['id', 'title', 'author', 'pages']]

"""Подсчет количества слов"""

len_one_book = len(one_book.split()) # делить по пробелам
len_one_book

words = re.sub(r'[.!?]', ' ', one_book) # удалить .!?
print(words.split())
print(len(words.split()))

def count_words_in_book(row):
    text = str(row['text'])
    words = re.sub(r'[.!?]', ' ', text)
    len_text = len(words.split())
    return len_text

book_df['word_count'] = book_df.apply(count_words_in_book, axis=1)

"""---- Статистика по словам"""

def words_in_book(b_id):
    b_text = book_df[book_df['id'] == b_id]['text'].astype(str).iloc[0]
    words = re.sub(r'[.!?]', ' ', b_text)
    return words.split()

def word_len_stat(b_id):
    words = words_in_book(b_id)
    lengths = np.array([len(w) for w in words])
    return (
        len(words),                # n_words
        float(np.mean(lengths)),   # mean
        int(np.min(lengths)),      # min
        int(np.max(lengths)),      # max
        float(np.median(lengths)), # median
        float(np.std(lengths)),    # std
    )

print(word_len_stat(1))

rows = []

for b_id in book_df['id']:
    n_words, w_mean, w_min, w_max, w_med, w_std = word_len_stat(b_id)
    rows.append({
        'id': b_id,
        'title': book_df.loc[book_df['id'] == b_id, 'title'].iloc[0],
        'n_words': n_words,
        'word_len_mean': w_mean,
        'word_len_min': w_min,
        'word_len_max': w_max,
        'word_len_median': w_med,
        'word_len_std': w_std,
    })

words_stats_df = pd.DataFrame(rows)

words_stats_df = words_stats_df.set_index('id')

words_stats_df[['id', 'title', 'word_len_mean', 'word_len_min', 'word_len_max', 'word_len_median', 'word_len_std']]

'''------------ОБНОВЛЕНИЕ words_stats_df------------'''
words_stats_df.to_csv('/b_word_stats.csv', index=True, encoding='utf-8')

'''------------ЗАГРУЗКА words_stats_df------------'''
w_csv_path = '/b_word_stats.csv'
words_stats_df = pd.read_csv(w_csv_path)

words_stats_df

"""Список длинных слов"""

w_lst =  words_in_book(1)
longest_words_lst = [w for w in w_lst if len(w) > 20 ]

longest_words_lst

longest_words_in_books = []
for ind in range(1,11):
    w_lst =  words_in_book(ind)
    longest_words_lst = [w for w in w_lst if len(w) > 20]
    longest_words_in_books.append(longest_words_lst)

for i, lst in enumerate(longest_words_in_books):
    print(f'Book id № {i+1}: {lst}')

"""### Статистика по предложениям

Подсчет количества предложений
"""

# деление по точкам некорректно
len_sent_book = len(one_book.split(". "))
print(len_sent_book)

# учитывает разное количество пробелов и переводов строк после точек
pattern = r'\.\s+'
sentences = re.split(pattern, one_book)
print(sentences[10:])

len(sentences)

pattern_new = r'[.!?]+[\s\n]+'
sentences = re.split(pattern_new, one_book)
print(sentences[10:])

len(sentences)   ## но не убраны пустые строки

def count_sent_in_book(row):
    text = str(row['text'])
    pattern = r'[.!?]+[\s\n]+'
    sentences = [s for s in re.split(pattern, text) if s.strip()] # убирает пустые строки
    return len(sentences)

book_df['sent_count'] = book_df.apply(count_sent_in_book, axis=1)

"""### Деление на датасеты по языкам"""

cols = ['id', 'title', 'author', 'year', 'pages', 'word_count', 'annotation_clean', 'text_clean', 'annotation', 'text']
en_analyze_df = book_df.loc[book_df['language'] == 'en', cols].copy()
ru_analyze_df = book_df.loc[book_df['language'] == 'ru', cols].copy()

"""### Подсчет слогов

Подсчет слогов в английском
"""

def count_sent_in_book(row):
    text = str(row['text'])
    pattern = r'[.!?]+[\s\n]+'
    sentences = [s for s in re.split(pattern, text) if s.strip()] # убирает пустые строки
    return len(sentences)

VOWELS = "aeiouy"

def count_syllables_word(word: str) -> int:
    word = word.lower()
    word = re.sub(r'[^a-z]', '', word)
    if not word:
        return 0

    count = 0
    if word[0] in VOWELS:
        count += 1
    for i in range(1, len(word)):
        if word[i] in VOWELS and word[i-1] not in VOWELS:
            count += 1
    if word.endswith("e"):
        count -= 1
    if word.endswith("le") and len(word) > 2 and word[-3] not in VOWELS:
        count += 1
    if count <= 0:
        count = 1
    return count


def count_syllables_text(text: str) -> int:
    if pd.isna(text):
        return 0
    words = re.findall(r"[A-Za-z']+", str(text))
    return sum(count_syllables_word(w) for w in words)

en_analyze_df['n_syll'] = en_analyze_df['text'].apply(count_syllables_text)

'''------------ЗАГРУЗКА en_analyze_df------------'''
en_a_csv_path = '/en_analyze_csv.csv'
en_analyze_df = pd.read_csv(en_a_csv_path)

'''------------ОБНОВЛЕНИЕ en_analyze_df------------'''
en_analyze_df.to_csv('/en_analyze_csv.csv', index=False, encoding='utf-8')

# подсчет слогов в русском слове / предложении
VOWELS_RU = "аеёиоуыэюя"
def count_syllables_word_ru(word: str) -> int:
    word = word.lower()
    # оставляем только русские буквы
    word = re.sub(r'[^а-яё]', '', word)

    if not word:
        return 0

    # число слогов = количество гласных
    count = sum(1 for ch in word if ch in VOWELS_RU)

    if count <= 0:
        count = 1
    return count

def count_syllables_text_ru(text: str) -> int:
    if pd.isna(text):
        return 0
    # слова как последовательности русских букв
    words = re.findall(r"[А-Яа-яЁё]+", str(text))
    return sum(count_syllables_word_ru(w) for w in words)

ru_analyze_df['n_syll'] = ru_analyze_df['text'].apply(count_syllables_text_ru)

'''------------ЗАГРУЗКА ru_analyze_df------------'''
ru_a_csv_path = '/ru_analyze_csv.csv'
ru_analyze_df = pd.read_csv(ru_a_csv_path)

'''------------ОБНОВЛЕНИЕ ru_analyze_df------------'''
ru_analyze_df.to_csv('/ru_analyze_csv.csv', index=False, encoding='utf-8')

"""### Индекс читаемости"""

!pip install textstat natasha -q

!python -m spacy download ru_core_news_sm

import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import textstat
import spacy
from natasha import Segmenter, MorphVocab, NewsEmbedding, NewsMorphTagger, Doc

# Английский
nlp_en = spacy.load("en_core_web_sm")
nlp_ru = spacy.load('ru_core_news_sm')

# Русский (Natasha)
segmenter = Segmenter()
morph_vocab = MorphVocab()
emb = NewsEmbedding()
morph_tagger = NewsMorphTagger(emb)

en_analyze_df[en_analyze_df['id'] == 1]['text'].astype(str).iloc[0]

# ─── Вспомогательные функции для русского ───────────────────────────────────

VOWELS_RU = re.compile(r'[аеёиоуыьъэюяАЕЁИОУЫЬЪЭЮЯ]')
SENT_SPLIT_RU = re.compile(r'[.!?]+')
WORD_RE = re.compile(r'\b\w+\b')

def count_syllables_ru(word: str) -> int:
    return len(VOWELS_RU.findall(word))

def avg_syllables_per_word_ru(text: str) -> float:
    words = WORD_RE.findall(text)
    if not words:
        return 0.0
    return sum(count_syllables_ru(w) for w in words) / len(words)

def flesh_ru(text: str) -> float:
    """Адаптированный индекс Флеша для русского."""
    sents = [s.strip() for s in SENT_SPLIT_RU.split(text) if s.strip()]
    words = WORD_RE.findall(text)
    if not sents or not words:
        return 0.0
    asl = len(words) / len(sents)          # средняя длина предложения
    asw = avg_syllables_per_word_ru(text)  # среднее кол-во слогов
    return 206.835 - 1.3 * asl - 60.1 * asw

def smog_ru(text: str) -> int:
    """SMOG grade для русского (приближение)."""
    sents = [s.strip() for s in SENT_SPLIT_RU.split(text) if s.strip()]
    words = WORD_RE.findall(text)
    if len(sents) < 3:
        return 0
    polysyl = sum(1 for w in words if count_syllables_ru(w) >= 3)
    return int(3 + np.sqrt(polysyl * (30 / len(sents))))

# ─── Основная функция ────────────────────────────────────────────────────────

def compute_readability(text: str, lang: str = 'en') -> dict:
    text = str(text)
    if lang == 'en':
        return {
            'flesch_reading_ease':   textstat.flesch_reading_ease(text),
            'flesch_kincaid_grade':  textstat.flesch_kincaid_grade(text),
            'gunning_fog':           textstat.gunning_fog(text),
            'smog_index':            textstat.smog_index(text),
            'automated_readability': textstat.automated_readability_index(text),
            'dale_chall':            textstat.dale_chall_readability_score(text),
        }
    else:  # ru
        return {
            'flesch_ru':  flesh_ru(text),
            'smog_ru':    smog_ru(text),
            'avg_syl_per_word': avg_syllables_per_word_ru(text),
            'avg_sent_len': len(WORD_RE.findall(text)) /
                            max(1, len([s for s in SENT_SPLIT_RU.split(text) if s.strip()])),
        }

rows = []

for b_id in ru_analyze_df['id']:
    rows.append({
        'id': b_id,
        'title': ru_analyze_df.loc[ru_analyze_df['id'] == b_id, 'title'].iloc[0],
        'text': ru_analyze_df.loc[ru_analyze_df['id'] == b_id, 'text'].iloc[0]

    })

readability_ru_df = pd.DataFrame(rows)

'''------------ЗАГРУЗКА readability_en_df------------'''
readability_en_df_path = '/readability_en_df.csv'
readability_en_df = pd.read_csv(readability_en_df_path)

'''------------СОХРАНЕНИЕ readability_en_df------------'''
readability_en_df.to_csv('/readability_en_df.csv', index=False, encoding='utf-8')

'''------------ЗАГРУЗКА readability_ru_df------------'''
readability_ru_df_path = '/readability_ru_df.csv'
readability_ru_df = pd.read_csv(readability_ru_df_path)

'''------------СОХРАНЕНИЕ readability_ru_df------------'''
readability_ru_df.to_csv('/readability_ru_df.csv', index=False, encoding='utf-8')

def clean_for_readability(text: str) -> str:
    """
    Очищает текст от технической разметки, заголовков глав/частей,
    лишних переносов и пробелов для корректного анализа читаемости.
    """
    text = str(text)

    # 1. Убираем заголовки глав и частей (EN + RU, регистронезависимо)
    # chapter_patterns = [
    #     r'(^|\n)\s*part\s+[a-z0-9ivx]+[^\n]*',
    #     r'(^|\n)\s*chapter\s+[a-z0-9ivx]+[^\n]*',
    #     r'(^|\n)\s*глава\s+[а-яё0-9ivx]+[^\n]*',
    #     r'(^|\n)\s*часть\s+[а-яё0-9ivx]+[^\n]*',
    # ]

    chapter_patterns = [
        r'\b(part|chapter)\s*[a-z0-9ivxlcdm]*\.?',
        r'\b(prologue|epilogue)\.?',
        r'\b(глава|часть|книга|раздел)\s*[а-яёa-z0-9]*\.?',
        r'\b(эпилог|пролог)\.?',
    ]
    for pat in chapter_patterns:
        text = re.sub(pat, ' ', text, flags=re.IGNORECASE)

    # 2. Убираем HTML/XML теги
    text = re.sub(r'<[^>]+>', ' ', text)

    # 3. Убираем URL
    text = re.sub(r'https?://\S+', ' ', text)

    # 4. Табуляции → пробел
    text = re.sub(r'\t', ' ', text)

    # 5. Переносы строк: одиночный \n → пробел (продолжение предложения),
    #    двойной \n\n → точка + пробел (граница абзаца, важно для читаемости)
    text = re.sub(r'\n{2,}', '. ', text)
    text = re.sub(r'\n', ' ', text)

    # 6. Специальные пробельные символы Unicode (\xa0, \u200b и др.) → пробел
    text = re.sub(r'[\xa0\u200b\u200c\u200d\ufeff]', ' ', text)

    # 7. Множественные пробелы → один
    text = re.sub(r' {2,}', ' ', text)

    return text.strip()

# Применение к датасетам
readability_en_df['text_for_readability'] = readability_en_df['text'].apply(clean_for_readability)
readability_ru_df['text_for_readability'] = readability_ru_df['text'].apply(clean_for_readability)

# Пересчёт индексов читаемости по очищенному тексту
readability_en = readability_en_df['text_for_readability'].apply(lambda t: compute_readability(t, lang='en'))
readability_en_df[['flesch_reading_ease','flesch_kincaid_grade','gunning_fog',
               'smog_index','automated_readability','dale_chall']] = pd.DataFrame(readability_en.tolist())

readability_ru = readability_ru_df['text_for_readability'].apply(lambda t: compute_readability(t, lang='ru'))
readability_ru_df[['flesch_ru','smog_ru','avg_syl_per_word','avg_sent_len']] = pd.DataFrame(readability_ru.tolist())

"""### TTR — Type-Token Ratio"""

def compute_ttr(text: str) -> float:
    words = re.findall(r'\b\w+\b', str(text).lower())
    if not words:
        return 0.0
    return len(set(words)) / len(words)

# Вариант MATTR (скользящее окно, устойчивее к длине текста)
def compute_mattr(text: str, window: int = 500) -> float:
    words = re.findall(r'\b\w+\b', str(text).lower())
    if len(words) < window:
        return compute_ttr(text)
    ttrs = [
        len(set(words[i:i+window])) / window
        for i in range(0, len(words) - window + 1, window)
    ]
    return float(np.mean(ttrs))

en_analyze_df['ttr']   = en_analyze_df['text_clean'].apply(compute_ttr)
en_analyze_df['mattr'] = en_analyze_df['text_clean'].apply(compute_mattr)

ru_analyze_df['ttr']   = ru_analyze_df['text_clean'].apply(compute_ttr)
ru_analyze_df['mattr'] = ru_analyze_df['text_clean'].apply(compute_mattr)

en_analyze_df.info()

ru_analyze_df.info()

"""### POS состав"""

# Один словарь для EN и RU
UPOS_NAMES = {
    'NOUN': 'Существительное', 'PROPN': 'Имя собственное',
    'VERB': 'Глагол',          'AUX':  'Вспомогат. глагол',
    'ADJ':  'Прилагательное',  'ADV':  'Наречие',
    'PRON': 'Местоимение',     'DET':  'Определитель',
    'ADP':  'Предлог',         'CCONJ':'Сочинит. союз',
    'SCONJ':'Подчинит. союз',  'NUM':  'Числительное',
    'PART': 'Частица',         'INTJ': 'Междометие',
    'PUNCT':'Пунктуация',      'X':    'Другое',
    'SPACE':'Пробел',
}

# ─── Universal Dependencies UPOS (русский, Natasha) ──────────────────────────
def pos_stats_ru(text: str, sample_chars: int = 100_000) -> dict:
    doc = Doc(str(text))
    doc.segment(segmenter)
    doc.tag_morph(morph_tagger)
    counts = {}
    for token in doc.tokens:
        pos = token.pos
        if pos:
            counts[pos] = counts.get(pos, 0) + 1
    return counts

# ─── POS-теги Penn Treebank (английский, spaCy) ──────────────────────────────
def pos_stats_en(text: str, sample_chars: int = 100_000) -> dict:
    doc = nlp_en(str(text))
    counts = {}
    for token in doc:
        if not token.is_space and not token.is_punct:
            counts[token.pos_] = counts.get(token.pos_, 0) + 1
    return counts

en_analyze_df['pos_dist'] = en_analyze_df['text_clean'].apply(pos_stats_en)

ru_analyze_df['pos_dist'] = ru_analyze_df['text_clean'].apply(pos_stats_ru)

for i in range(1,6):
    print(f'{i}.: {en_analyze_df[en_analyze_df['id'] == i]['pos_dist_100k'].astype(str).iloc[0]}')

for i in range(1,6):
    print(f'{i}.: {en_analyze_df[en_analyze_df['id'] == i]['pos_dist'].astype(str).iloc[0]}')

for i in range(1,6):
    print(f'{i}.: {ru_analyze_df[ru_analyze_df['id'] == i]['pos_dist_100k'].astype(str).iloc[0]}')

for i in range(1,6):
    print(f'{i}.: {ru_analyze_df[ru_analyze_df['id'] == i]['pos_dist'].astype(str).iloc[0]}')

def specific_pos_words_en(text: str, pos, sample_chars: int = 50_000) -> dict:
    doc = nlp_en(str(text))
    pos_words = []
    for token in doc:
        if token.pos_ == pos:
            pos_words.append(token)
    return pos_words

for text in en_analyze_df['text_clean']:
    lst = specific_pos_words_en(text, pos = 'IN')
    print(f'{len(lst)}: {lst})')

one_book = en_analyze_df[en_analyze_df['id'] == 1]['text_clean'].astype(str).iloc[0]

doc = nlp_en(str(one_book))

print(len(one_book)) #количество символов

print(len(doc)) #количество токенов

unique_tokens = set(token.text for token in doc)  #уникальные токены
print(len(unique_tokens))

"""### Частотность слов

### Топ-10 слов
"""

import pandas as pd
from collections import Counter
import re
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

stop_en = set(stopwords.words('english'))
stop_ru = set(stopwords.words('russian'))

def get_top10(text, lang='en'):
    stops = stop_en if lang == 'en' else stop_ru
    words = re.findall(r'\b[a-zA-Zа-яёА-ЯЁ]+\b', text.lower())
    words = [w for w in words if w not in stops]
    return Counter(words).most_common(10)

for _, row in readability_en_df.iterrows():
    print(f"\n📖 {row['title']}")
    top10 = get_top10(row['text_for_readability'], lang='en')
    for word, count in top10:
        print(f"  {word}: {count}")

"""В английском"""

one_book = readability_en_df[readability_en_df['id'] == 5]['text_for_readability'].astype(str).iloc[0]

file_path = one_book

from collections import defaultdict
import re
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
stop_en = set(stopwords.words('english'))
stop_ru = set(stopwords.words('russian'))

# Токенизируем строку one_book в слова
words = re.findall(r'\b[a-zA-Z]+\b', one_book.lower())
words = [w for w in words if w not in stop_en]

word_freq = defaultdict(int)
for word in words:          # итерируемся по словам, не по предложениям
    word_freq[word] += 1

total_words = sum(word_freq.values())
print(f"Общее количество слов в словаре: {len(word_freq)}")

def top_k_words(k):
    print(f"\nТоп-{k} самых частотных слов и их частота:")
    for word, freq in sorted(word_freq.items(), key=lambda x: x[1], reverse=True)[:k]:
        print(f"({word}, {freq})")
print("Книга №5")
top_k_words(15)

"""В русском"""

def lemmatize_and_count(text):
    words = re.findall(r'\b[а-яёА-ЯЁ]+\b', text.lower())
    lemmas = [morph.parse(w)[0].normal_form for w in words]
    lemmas = [w for w in lemmas if w not in stop_ru]

    word_freq = defaultdict(int)
    for lemma in lemmas:
        word_freq[lemma] += 1
    return word_freq

top15_results = {}
wordfreq_results = {}

for _, row in readability_ru_df.iterrows():
    word_freq = lemmatize_and_count(str(row['text_for_readability']))

    top15 = sorted(word_freq.items(), key=lambda x: x[1], reverse=True)[:15]
    top15_results[row['title']] = top15
    wordfreq_results[row['title']] = word_freq

# Вывод
for title, top15 in top15_results.items():
    wf = wordfreq_results[title]  # берём word_freq конкретной книги
    print(f"\n📖 {title}")
    print(f"Всего токенов: {sum(wf.values())}")
    print(f"Уникальных слов: {len(wf)}")
    for word, freq in top15:
        print(f"  ({word}: {freq})")

"""### Подсчет существительных и глаголов **'love/любовь/любить'**"""

!pip install pymorphy3

import pymorphy3 as pm3
morph = pm3.MorphAnalyzer()

from collections import defaultdict
import re
import nltk
from nltk.corpus import stopwords

nltk.download('averaged_perceptron_tagger_eng')
nltk.download('punkt_tab')
nltk.download('stopwords')
stop_en = set(stopwords.words('english'))
stop_ru = set(stopwords.words('russian'))

nlp_en = spacy.load("en_core_web_sm")
nlp_ru = spacy.load('ru_core_news_sm')

"""Подсчет в **английском** покорпусе"""

### вместе ###

target = 'love'
results = []

for _, row in en_analyze_df.iterrows():
    # Токенизируем текст каждой книги
    words = re.findall(r'\b[a-zA-Z]+\b', str(row['text_clean']).lower())

    # Считаем word_freq для этой книги
    word_freq = defaultdict(int)
    for word in words:
        word_freq[word] += 1

    results.append({
        'id': row['id'],
        'title': row['title'],
        'love_freq': word_freq.get(target, 0)
    })

love_df = pd.DataFrame(results)
love_df

def count_love_pos_spacy(doc):
    counts = defaultdict(int)
    for token in doc:
        if token.lemma_.lower() == 'love':
            if token.tag_.startswith('NN'):   # NN, NNP, NNS, NNPS
                counts['noun'] += 1
            elif token.tag_.startswith('VB'): # VB, VBP, VBD, VBG, VBN, VBZ
                counts['verb'] += 1
    return counts

results = []
for _, row in en_analyze_df.iterrows():
    doc = nlp_en(str(row['text_clean']))
    counts = count_love_pos_spacy(doc)
    results.append({
        'id': row['id'],
        'title': row['title'],
        'love_noun': counts['noun'],
        'love_verb': counts['verb'],
    })

love_pos_df = pd.DataFrame(results)
love_pos_df

love_pos_df

"""Подсчет в **русском** покорпусе"""

def lemmatize_and_count(text):
    words = re.findall(r'\b[а-яёА-ЯЁ]+\b', text.lower())
    lemmas = [morph.parse(w)[0].normal_form for w in words]
    lemmas = [w for w in lemmas if w not in stop_ru]

    word_freq = defaultdict(int)
    for lemma in lemmas:
        word_freq[lemma] += 1
    return word_freq

results = []

for _, row in ru_analyze_df.iterrows():
    word_freq = lemmatize_and_count(str(row['text_clean']))

    results.append({
        'id': row['id'],
        'title': row['title'],
        'любовь_freq': word_freq.get('любовь', 0),
        'любить_freq': word_freq.get('любить', 0),
    })

love_ru_df = pd.DataFrame(results)

love_ru_df

"""#### ВИзуализация"""

def plot_book_distribution(df: pd.DataFrame, col: str, xlabel: str,
                           title: str, lang_col: str = 'language',
                           en_val: str = 'en', ru_val: str = 'ru'):
    """
    Горизонтальные столбцы для каждой книги из одного датафрейма.
    EN — синие (левая панель), RU — красные (правая панель).
    """
    en_df = df[df[lang_col] == en_val].copy()
    ru_df = df[df[lang_col] == ru_val].copy()

    fig, axes = plt.subplots(1, 2, figsize=(16, 5))

    for ax, sub_df, lang, color in zip(
        axes,
        [en_df, ru_df],
        ['EN', 'RU'],
        ['steelblue', 'tomato']
    ):
        sub_df = sub_df.sort_values(col)
        labels = sub_df['title'].values
        values = sub_df[col].values

        bars = ax.barh(labels, values, color=color)
        for bar in bars:
            w = bar.get_width()
            ax.text(w * 1.01, bar.get_y() + bar.get_height() / 2,
                    f'{int(w):,}', va='center', fontsize=9)

        ax.set_title(f'{title} ({lang})', fontsize=13)
        ax.set_xlabel(xlabel)
        ax.grid(axis='x', linestyle='--', alpha=0.6)

    plt.tight_layout()
    plt.show()

# ── Год издания ──────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 4))
for ax, lang, color in zip(axes, ['en', 'ru'], ['steelblue', 'tomato']):
    sub = book_df[book_df['language'] == lang]
    year_counts = sub['year'].value_counts().sort_index()
    ax.bar(year_counts.index.astype(str), year_counts.values, color=color)
    for i, v in enumerate(year_counts.values):
        ax.text(i, v + 0.05, str(v), ha='center', fontsize=10)
    ax.set_title(f'Год издания ({lang.upper()})', fontsize=13)
    ax.set_xlabel('Год')
    ax.set_ylabel('Кол-во книг')
    ax.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

# ── Количество слов ──────────────────────────────────────────────────────────
plot_book_distribution(book_df, col='word_count',
                       xlabel='Количество слов',
                       title='Объём книг (слова)')

# ── Количество предложений ───────────────────────────────────────────────────
plot_book_distribution(book_df, col='sent_count',
                       xlabel='Количество предложений',
                       title='Объём книг (предложения)')

def plot_book_distribution_2df(en_df: pd.DataFrame, ru_df: pd.DataFrame,
                           col: str, xlabel: str, title: str):
    """
    Горизонтальные столбцы для каждой книги EN и RU рядом.
    EN — синие, RU — красные.
    """
    fig, axes = plt.subplots(2, 1, figsize=(8, 10))

    for ax, df, lang, color in zip(
        axes,
        [en_df, ru_df],
        ['EN', 'RU'],
        ['steelblue', 'tomato']
    ):
        labels = df['title'].values
        values = df[col].values
        sorted_idx = np.argsort(values)
        labels = labels[sorted_idx]
        values = values[sorted_idx]

        bars = ax.barh(labels, values, color=color)
        for bar in bars:
            w = bar.get_width()
            # ax.text(w * 1.01, bar.get_y() + bar.get_height()/2,
            #         f'{int(w):,}', va='center', fontsize=9)

        ax.set_title(f'{title} ({lang})', fontsize=13)
        ax.set_xlabel(xlabel)
        ax.grid(axis='x', linestyle='--', alpha=0.6)

    plt.tight_layout()
    plt.show()

plot_book_distribution_2df(en_analyze_df, ru_analyze_df,
                       col='ttr',
                       xlabel='ttr',
                       title='Type-of-Token')

plot_book_distribution_2df(en_analyze_df, ru_analyze_df,
                       col='mattr',
                       xlabel='mattr',
                       title='Moving Average Type-Token Ratio (скользящее среднее значение TTR)')

def plot_pos_pie(pos_dict: dict, title: str, label_map: dict = None,
                threshold: float = 0.03, pct_threshold: float = 0.05):
    """
    pct_threshold — минимальная доля для отображения % внутри сектора.
                    Для маленьких секторов процент скрывается.
    """
    if label_map is None:
        label_map = {}

    total = sum(pos_dict.values())
    if total == 0:
        print(f"[{title}] Пустой словарь, пропускаем.")
        return

    renamed = {}
    other_sum = 0
    other_details = {}

    for pos, count in pos_dict.items():
        name = label_map.get(pos, pos)
        share = count / total
        if share < threshold:
            other_sum += count
            other_details[name] = round(share * 100, 1)
        else:
            renamed[name] = renamed.get(name, 0) + count

    if other_sum > 0:
        renamed['Другое'] = other_sum

    if not renamed:
        print(f"[{title}] Все категории < {threshold*100}%, снизь threshold.")
        return

    sorted_pos = dict(sorted(renamed.items(), key=lambda x: x[1], reverse=True))
    values = list(sorted_pos.values())
    labels = list(sorted_pos.keys())
    colors = plt.cm.Paired(np.linspace(0, 1, len(sorted_pos)))

    fig, ax = plt.subplots(figsize=(10, 7))

    # Показываем % только для секторов выше pct_threshold
    def autopct_fn(pct):
        return f'{pct:.1f}%' if pct / 100 >= pct_threshold else ''

    wedges, _, autotexts = ax.pie(
        values,
        labels=None,
        autopct=autopct_fn,          # ← умная функция вместо строки формата
        startangle=90,
        colors=colors,
        textprops={'fontsize': 11},
        pctdistance=0.75,            # ← подписи ближе к центру
    )

    for at in autotexts:
        at.set_color('white')
        at.set_fontweight('bold')

    # Добавляем % в легенду
    legend_labels = [
        f"{name} ({v/total*100:.1f}%)" for name, v in sorted_pos.items()
    ]
    ax.legend(
        wedges, legend_labels,
        title='Части речи',
        loc='center left',
        bbox_to_anchor=(1, 0, 0.5, 1),
        fontsize=10
    )

    ax.set_title(title, fontsize=15)
    ax.axis('equal')
    plt.tight_layout()
    plt.show()

    if other_details:
        print(f"\nКатегория 'Другое' ({title}):")
        for name, pct in sorted(other_details.items(), key=lambda x: -x[1]):
            print(f"  {name}: {pct}%")

"""**!!!** *При сохранении DataFrame через CSV словари превращаются в строки.*"""

en_analyze_df['pos_dist']

print(type(en_analyze_df['pos_dist'].iloc[0]))

import ast

# Конвертировать колонку из строк в словари
en_analyze_df['pos_dist'] = en_analyze_df['pos_dist'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)

ru_analyze_df['pos_dist'] = ru_analyze_df['pos_dist'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)

print(type(en_analyze_df['pos_dist'].iloc[0]))

"""**!!!** *Теперь должно работать*"""

# Суммарное распределение по всем книгам
combined_en_pos = {}
for pos_d in en_analyze_df['pos_dist']:
    for k, v in pos_d.items():
        combined_en_pos[k] = combined_en_pos.get(k, 0) + v

combined_ru_pos = {}
for pos_d in ru_analyze_df['pos_dist']:
    for k, v in pos_d.items():
        combined_ru_pos[k] = combined_ru_pos.get(k, 0) + v

plot_pos_pie(combined_en_pos, "POS-состав (английские романы)", UPOS_NAMES,  threshold=0.01)

plot_pos_pie(combined_ru_pos, "POS-состав (русские романы)",    UPOS_NAMES,  threshold=0.01)

# Для отдельной книги
for _, row in en_analyze_df.iterrows():
    plot_pos_pie(row['pos_dist'], f"POS: {row['title']}", UPOS_NAMES)

# Для отдельной книги
for _, row in ru_analyze_df.iterrows():
    plot_pos_pie(row['pos_dist'], f"POS: {row['title']}", UPOS_NAMES)

"""## Тематическое моделирование BERTopic по **аннотациям**"""

!pip install bertopic

from bertopic.representation import PartOfSpeech
from bertopic import BERTopic
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer

pos_patterns = [
    [{'POS': 'NOUN'}],                        # существительные
    [{'POS': 'VERB'}],                        # глаголы
    [{'POS': 'ADJ'}],                         # прилагательные
    [{'POS': 'ADV'}],                         # наречия
    [{'POS': 'ADJ'}, {'POS': 'NOUN'}],        # "горькая любовь", "broken heart"
    [{'POS': 'NOUN'}, {'POS': 'NOUN'}],       # "призрак прошлого", "heart rate"
    [{'POS': 'ADV'}, {'POS': 'ADJ'}]          # "deeply afraid"
]

"""### Моделирование по аннотациям **на английском**"""

docs_e = en_analyze_df['annotation'].astype(str).tolist()

# Разбить на предложения через spaCy (сохраняя пунктуацию!)
docs_e = [sent.text.strip() for book_text in docs_e
        for sent in nlp_en(book_text).sents
        if len(sent.text.strip()) > 10]

print(f"Число документов (предложений): {len(docs_e)}")
print(docs_e[:3])

n = len(docs_e)

umap_model = UMAP(
    n_neighbors=min(5, n - 1),  # для малого корпуса уменьшаем
    n_components=2,
    min_dist=0.0,
    metric='cosine',
    init='random'
)

hdbscan_model = HDBSCAN(
    min_cluster_size=2,       # для малого корпуса минимум 2
    min_samples=1,
    prediction_data=True
)

representation_model = PartOfSpeech(
    model="en_core_web_sm",
    top_n_words=10,
    pos_patterns=pos_patterns
)

vectorizer = CountVectorizer(
    stop_words="english",
    min_df=1,
    token_pattern=r"(?u)\b[a-zA-Z][a-zA-Z]{3,}\b"  # только слова от 2 букв
)

topic_model_en = BERTopic(
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    representation_model=representation_model,
    vectorizer_model=vectorizer,
    calculate_probabilities=True,
    language="english"
)

topics, probs = topic_model_en.fit_transform(docs_e)

"""Изначально модель построила 13 (12) топиков, но визульно их можно поделить на 3"""

topic_model_en.get_topic_info()

topic_model_en.visualize_topics()

all_topics = topic_model_en.get_topics()

for topic_id, words in all_topics.items():
    word_list = [w for w, _ in words]
    print(f"Тема {topic_id}: {word_list}")

"""Сокращение до 3"""

topic_model_en = topic_model_en.reduce_topics(docs_e, nr_topics=4)
topic_model_en.get_topic_info()

topic_model_en.visualize_topics()

all_topics = topic_model_en.get_topics()

for topic_id, words in all_topics.items():
    word_list = [w for w, _ in words]
    print(f"Тема {topic_id}: {word_list}")

topic_model_en.visualize_barchart(n_words=8)

# Посмотреть документы каждой темы
topic_model_en.visualize_documents(docs_e)

"""### Моделирование по аннотациям **на русском**"""

import re

def clean_text_ru(text):
    # Убрать заголовки глав (русские варианты)
    text = re.sub(r'(Часть\s+\w+|Глава\s+\w+|Пролог|Эпилог)', '', text, flags=re.IGNORECASE)
    text = text.replace('\r', ' ')
    text = text.replace('\n', ' ')
    text = text.replace('\t', ' ')
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

docs_r = []

for row in ru_analyze_df['annotation'].astype(str):
    book_text = clean_text_ru(row)
    for sent in nlp_ru(book_text).sents:
        text = clean_text_ru(sent.text)
        if len(text.split()) > 5:
            docs_r.append(text)

print(f"Число документов (предложений): {len(docs_r)}")
print(docs_r[:3])

n = len(docs_r)

umap_model = UMAP(
    n_neighbors=min(5, n - 1),
    n_components=2,
    min_dist=0.0,
    metric='cosine',
    init='random'
)

hdbscan_model = HDBSCAN(
    min_cluster_size=2,
    min_samples=1,
    prediction_data=True
)

representation_model = PartOfSpeech(
    model="ru_core_news_sm",
    top_n_words=10,
    pos_patterns=pos_patterns

)

vectorizer = CountVectorizer(
    min_df=1,
    token_pattern=r"(?u)\b[а-яёА-ЯЁ][а-яёА-ЯЁ]{3,}\b"
)

topic_model = BERTopic(
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    representation_model=representation_model,
    vectorizer_model=vectorizer,
    calculate_probabilities=True,
    language="multilingual"   # multilingual лучше для русского
)

topics, probs = topic_model.fit_transform(docs_r)

"""Изначально было 12 (11) тем"""

topic_model.get_topic_info()

topic_model.visualize_topics()

all_topics = topic_model.get_topics()

for topic_id, words in all_topics.items():
    word_list = [w for w, _ in words]
    print(f"Тема {topic_id}: {word_list}")

"""Сокращение до 4 тем"""

topic_model_reduced = topic_model.reduce_topics(docs_r, nr_topics=5)

# Применить vectorizer с POS-фильтрацией заново
topic_model_reduced.update_topics(
    docs_r,
    vectorizer_model=vectorizer,
    representation_model=representation_model
)

topic_model_reduced.get_topic_info()

topic_model.visualize_topics()

all_topics = topic_model.get_topics()

for topic_id, words in all_topics.items():
    word_list = [w for w, _ in words]
    print(f"Тема {topic_id}: {word_list}")

# Карта тем
topic_model.visualize_topics()

# Топ-слова каждой темы
topic_model.visualize_barchart(n_words=8)

# Посмотреть документы каждой темы
topic_model.visualize_documents(docs_r)

"""## Контекстный анализ лексем *love* и *любовь/любить* в двуязычном корпусе романтической прозы"""

import spacy
import pymorphy3
from collections import Counter, defaultdict
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
from matplotlib.gridspec import GridSpec
import re

matplotlib.rcParams['font.family'] = 'DejaVu Sans'

nlp_en = spacy.load('en_core_web_sm')
morph = pymorphy3.MorphAnalyzer()

WINDOW = 3  # окно ±3 слова

def get_love_contexts_en(texts: list, window: int = WINDOW):
    """
    Извлекает контекстные окна вокруг love-NOUN и love-VERB из EN текстов.
    texts — список строк (тексты книг)
    Возвращает два списка соседних лемм: для noun и для verb.
    """
    noun_context = []
    verb_context = []

    EN_STOP = {'not', 'i', 'd', 're', 've', 'm', 's',
                'the', 'a', 'an', 'it', 'be', 'do',
                'that', 'this', 'so', 'just', 'get'
                }

    for text in texts:
        doc = nlp_en(str(text))
        tokens = list(doc)
        for i, token in enumerate(tokens):
            if token.lemma_.lower() != 'love':
                continue
            # Соседи в окне
            left  = tokens[max(0, i - window): i]
            right = tokens[i + 1: i + 1 + window]
            neighbors = [t.lemma_.lower() for t in left + right
                         if not t.is_punct and not t.is_space
                         and t.lemma_.lower() not in EN_STOP
                         and len(t.lemma_) > 1
                         and t.lemma_.lower() not in ('love',)]

            if token.pos_ == 'NOUN':
                noun_context.extend(neighbors)
            elif token.pos_ == 'VERB':
                verb_context.extend(neighbors)

    return noun_context, verb_context


def get_love_contexts_ru(texts: list, window: int = WINDOW):
    """
    Извлекает контекстные окна вокруг любовь (NOUN) и любить (VERB) из RU текстов.
    Использует pymorphy3 для лемматизации.
    """
    noun_context = []
    verb_context = []

    RU_STOP = {'и', 'в', 'на', 'с', 'по', 'к', 'за', 'из', 'не',
                 'то', 'а', 'но', 'же', 'бы', 'как', 'что', 'это',
                 'он', 'она', 'они', 'мы', 'я', 'ты', 'вы', 'его',
                 'ее', 'её', 'их', 'мне', 'меня', 'себя', 'себе',
                 'который', 'кто', 'мой', 'твой', 'свой', 'тот',
                'такой', 'весь', 'быть'}

    for text in texts:
        # Разбиваем на токены (слова)
        raw_tokens = re.findall(r'[а-яёА-ЯЁa-zA-Z]+', str(text))
        # Лемматизируем все токены
        lemmas = []
        pos_tags = []
        for w in raw_tokens:
            parsed = morph.parse(w.lower())[0]
            lemmas.append(parsed.normal_form)
            pos_tags.append(parsed.tag.POS)

        for i, (lemma, pos) in enumerate(zip(lemmas, pos_tags)):
            target_lemma = None
            target_type  = None

            if lemma == 'любовь':
                target_lemma = 'любовь'
                target_type  = 'noun'
            elif lemma == 'любить':
                target_lemma = 'любить'
                target_type  = 'verb'

            if target_lemma is None:
                continue

            left  = lemmas[max(0, i - window): i]
            right = lemmas[i + 1: i + 1 + window]
            neighbors = [l for l in left + right
                         if l not in RU_STOP and len(l) > 2
                         and l not in ('любовь', 'любить')]

            if target_type == 'noun':
                noun_context.extend(neighbors)
            else:
                verb_context.extend(neighbors)

    return noun_context, verb_context

en_texts = [en_analyze_df[en_analyze_df['id'] == i]['text_clean'].values[0] for i in en_analyze_df['id'].unique()]
ru_texts = [ru_analyze_df[ru_analyze_df['id'] == i]['text_clean'].values[0] for i in ru_analyze_df['id'].unique()]

en_noun_ctx, en_verb_ctx = get_love_contexts_en(en_texts)
ru_noun_ctx, ru_verb_ctx = get_love_contexts_ru(ru_texts)

TOP_N = 15

en_noun_freq = Counter(en_noun_ctx).most_common(TOP_N)
en_verb_freq = Counter(en_verb_ctx).most_common(TOP_N)
ru_noun_freq = Counter(ru_noun_ctx).most_common(TOP_N)
ru_verb_freq = Counter(ru_verb_ctx).most_common(TOP_N)

# Вывод таблиц
for label, freq in [('EN love-NOUN', en_noun_freq),
                     ('EN love-VERB', en_verb_freq),
                     ('RU любовь (NOUN)', ru_noun_freq),
                     ('RU любить (VERB)', ru_verb_freq)]:
    df = pd.DataFrame(freq, columns=['word', 'freq'])
    print(f"\n=== {label} ===")
    print(df.to_string(index=False))

fig = plt.figure(figsize=(16, 12))
fig.suptitle('Контекстное окружение лексемы LOVE/ЛЮБОВЬ в зависимости\nот частеречной функции (топ-15 соседних слов)',
             fontsize=14, fontweight='bold', y=0.98)

gs = GridSpec(2, 2, figure=fig, hspace=0.5, wspace=0.4)

panels = [
    (en_noun_freq, 'EN: love-NOUN\n(контекст существительного)', '#4C72B0', gs[0, 0]),
    (en_verb_freq, 'EN: love-VERB\n(контекст глагола)',           '#DD8452', gs[0, 1]),
    (ru_noun_freq, 'RU: любовь-NOUN\n(контекст существительного)','#55A868', gs[1, 0]),
    (ru_verb_freq, 'RU: любить-VERB\n(контекст глагола)',         '#C44E52', gs[1, 1]),
]

for freq_data, title, color, grid_pos in panels:
    ax = fig.add_subplot(grid_pos)
    if not freq_data:
        ax.text(0.5, 0.5, 'Нет данных', ha='center', va='center', transform=ax.transAxes)
        ax.set_title(title, fontsize=11, fontweight='bold')
        continue
    words  = [w for w, _ in freq_data][::-1]
    counts = [c for _, c in freq_data][::-1]
    bars = ax.barh(words, counts, color=color, alpha=0.85)
    ax.set_title(title, fontsize=11, fontweight='bold')
    ax.set_xlabel('Частота', fontsize=9)
    # Подписи значений
    for bar, val in zip(bars, counts):
        ax.text(val + 0.1, bar.get_y() + bar.get_height()/2,
                str(val), va='center', fontsize=8)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

plt.show()

